import { MIDIEvent } from "../MIDIEvent";
export declare const SEQUENCE_NUMBER = "sequence number";
export declare const TEXT = "text";
export declare const COPYRIGHT_NOTICE = "copyright notice";
export declare const TRACK_NAME = "track name";
export declare const INSTRUMENT_NAME = "instrument name";
export declare const LYRICS = "lyrics";
export declare const MARKER = "marker";
export declare const CUE_POINT = "cue point";
export declare const CHANNEL_PREFIX = "channel prefix";
export declare const END_OF_TRACK = "end of track";
export declare const TEMPO = "tempo";
export declare const SMPTE_OFFSET = "smpte offset";
export declare const TIME_SIGNATURE = "time signature";
export declare const KEY_SIGNATURE = "key signature";
export declare const SEQUENCER_SPECIFIC = "sequencer specific";
export declare const SYSTEM_EXCLUSIVE = "system exclusive";
export declare const DIVIDED_SYSTEM_EXCLUSIVE = "divided system exclusive";
export declare const NOTE_ON = "note on";
export declare const NOTE_OFF = "note off";
export declare const NOTE_AFTERTOUCH = "note aftertouch";
export declare const CONTROLLER = "controller";
export declare const PROGRAM_CHANGE = "program change";
export declare const CHANNEL_AFTERTOUCH = "channel aftertouch";
export declare const PITCH_BEND = "pitch bend";
export declare const noteNames: {
    sharp: string[];
    flat: string[];
    "enharmonic-sharp": string[];
    "enharmonic-flat": string[];
};
export declare const getMidiEventDescription: (type: number, subType?: number | undefined) => string;
export declare const getMidiMessageEvent: (event: MIDIEvent) => number[];
export declare const getNoteNumber: (name: string, octave: number, mode?: string) => number;
export declare const sortMIDIEvents: (events: MIDIEvent[]) => MIDIEvent[];
export declare const removeDoubleEvents: (events: MIDIEvent[]) => MIDIEvent[];
